# Generated by Django 3.0.8 on 2020-07-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200713_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='slug',
            field=models.SlugField(default='item-slug', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
