# Generated by Django 3.0.8 on 2020-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='cleaning-logo.png', null=True, upload_to='profile_pic'),
        ),
    ]
