# Generated by Django 3.0.8 on 2020-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200715_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='cleaning-logo.png', null=True, upload_to='media_root/profile_pic'),
        ),
    ]
